name: aad_oauth
description: A Flutter OAuth package for performing user authentication against
  Azure Active Directory OAuth2 v2.0 endpoint.
version: 1.0.1
homepage: https://github.com/Earlybyte/aad_oauth

environment:
  sdk: '^3.6.2'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  webview_flutter: ^4.10.0
  js: ^0.6.3
  http: ^1.1.0
  shared_preferences: ^2.2.1
  dartz: ^0.10.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/msalv2.js